"""empty message

Revision ID: 55d8a059bef8
Revises: 
Create Date: 2022-09-04 17:29:34.029535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d8a059bef8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tasks', sa.Column('skipped', sa.String(), nullable=False))
    op.alter_column('users_tasks', 'correct',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users_tasks', 'used_hint',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_tasks', 'used_hint',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users_tasks', 'correct',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users_tasks', 'skipped')
    # ### end Alembic commands ###
