"""empty message

Revision ID: 7c246108e08a
Revises: 55d8a059bef8
Create Date: 2022-09-05 23:20:46.139575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c246108e08a'
down_revision = '55d8a059bef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('About',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.Text(length=192), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('info')
    )
    op.create_table('Contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_source', sa.Text(length=96), nullable=True),
    sa.Column('info', sa.Text(length=192), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_source'),
    sa.UniqueConstraint('info')
    )
    op.create_table('Team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('profession', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('linkedin', sa.Text(), nullable=True),
    sa.Column('github', sa.Text(), nullable=True),
    sa.Column('dribble', sa.Text(), nullable=True),
    sa.Column('behance', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Team')
    op.drop_table('Contacts')
    op.drop_table('About')
    # ### end Alembic commands ###
