"""empty message

Revision ID: ea931ec45a3d
Revises: f56e7c3ebaa1
Create Date: 2022-09-06 00:15:14.138460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea931ec45a3d'
down_revision = 'f56e7c3ebaa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('About', sa.Column('about', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'About', ['about'])
    op.drop_column('About', 'info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('About', sa.Column('info', sa.TEXT(length=192), nullable=True))
    op.drop_constraint(None, 'About', type_='unique')
    op.drop_column('About', 'about')
    # ### end Alembic commands ###
