"""empty message

Revision ID: f56e7c3ebaa1
Revises: 7c246108e08a
Create Date: 2022-09-05 23:27:19.816762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56e7c3ebaa1'
down_revision = '7c246108e08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('person', sa.Text(), nullable=True))
    op.add_column('Team', sa.Column('position', sa.Text(), nullable=True))
    op.drop_column('Team', 'profession')
    op.drop_column('Team', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('full_name', sa.TEXT(), nullable=True))
    op.add_column('Team', sa.Column('profession', sa.TEXT(), nullable=True))
    op.drop_column('Team', 'position')
    op.drop_column('Team', 'person')
    # ### end Alembic commands ###
